import io
import logging
from datetime import datetime
from pathlib import Path
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT

from app.services.report_data import AnnualReportData

# Define branding colors
PRIMARY_COLOR = colors.HexColor("#1e3a8a")  # Dark blue
SECONDARY_COLOR = colors.HexColor("#3b82f6") # Blue
TEXT_COLOR = colors.HexColor("#1f2937") # Gray-800
LIGHT_GRAY = colors.HexColor("#f3f4f6") # Gray-100

def create_pdf_report(data: AnnualReportData) -> io.BytesIO:
    """
    Generates a professionally formatted PDF for the Annual Activity Report.
    Returns an io.BytesIO buffer containing the PDF data.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=letter,
        rightMargin=40, leftMargin=40,
        topMargin=50, bottomMargin=50
    )
    
    logo_path = Path(__file__).parent.parent / "assets" / "branding" / "iedc-logo.png"
    if not logo_path.exists():
        logging.error(f"Production asset missing: {logo_path}")
        raise FileNotFoundError(f"Missing required branding asset: {logo_path}")
    
    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=PRIMARY_COLOR,
        alignment=TA_CENTER,
        spaceAfter=20
    )
    subtitle_style = ParagraphStyle(
        'SubtitleStyle',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=SECONDARY_COLOR,
        alignment=TA_CENTER,
        spaceAfter=10
    )
    normal_style = ParagraphStyle(
        'NormalStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=TEXT_COLOR,
        spaceAfter=6,
        leading=14
    )
    section_header_style = ParagraphStyle(
        'SectionHeaderStyle',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=PRIMARY_COLOR,
        spaceBefore=15,
        spaceAfter=10,
        borderPadding=5
    )
    item_title_style = ParagraphStyle(
        'ItemTitleStyle',
        parent=styles['Heading3'],
        fontSize=12,
        textColor=TEXT_COLOR,
        spaceBefore=10,
        spaceAfter=5
    )
    bold_style = ParagraphStyle(
        'BoldStyle',
        parent=styles['Normal'],
        fontSize=10,
        fontName='Helvetica-Bold',
        textColor=TEXT_COLOR
    )

    story = []

    # ---------------------------------------------------------
    # 1. Cover Page
    # ---------------------------------------------------------
    story.append(Spacer(1, 60))
    
    # Official Logo
    logo = Image(str(logo_path), width=150, height=150)
    logo.hAlign = 'CENTER'
    story.append(logo)
    story.append(Spacer(1, 40))

    story.append(Paragraph("IEDC SNMIMT", title_style))
    story.append(Paragraph("ACTIVITY REPORT", subtitle_style))
    story.append(Spacer(1, 30))
    
    period_str = f"Reporting Period<br/>{data.start_date.strftime('%d %B %Y')} — {data.end_date.strftime('%d %B %Y')}"
    story.append(Paragraph(period_str, subtitle_style))
    story.append(Spacer(1, 30))
    
    generated_str = f"Generated On<br/>{data.generated_at.strftime('%d %B %Y, %H:%M UTC')}<br/><br/>Generated By<br/>{data.generated_by}"
    story.append(Paragraph(generated_str, ParagraphStyle(
        'MetaStyle', parent=normal_style, alignment=TA_CENTER, fontSize=11, spaceBefore=20
    )))
    
    story.append(PageBreak())

    # ---------------------------------------------------------
    # 2. Executive Summary
    # ---------------------------------------------------------
    story.append(Paragraph("EXECUTIVE SUMMARY", section_header_style))
    
    summary_data = [
        ["Metric", "Total Count"],
        ["Events", str(data.summary.total_events)],
        ["Registrations", str(data.summary.total_registrations)],
        ["Startups", str(data.summary.total_startups)],
        ["Podcasts", str(data.summary.total_podcasts)],
        ["Announcements", str(data.summary.total_announcements)],
        ["Gallery Activities", str(data.summary.total_gallery)]
    ]
    
    t = Table(summary_data, colWidths=[200, 100])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), PRIMARY_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('TEXTCOLOR', (0, 1), (-1, -1), TEXT_COLOR),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, LIGHT_GRAY),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, LIGHT_GRAY])
    ]))
    story.append(t)
    story.append(PageBreak())

    # ---------------------------------------------------------
    # 3. Events Section
    # ---------------------------------------------------------
    story.append(Paragraph("1. EVENTS", section_header_style))
    if not data.events:
        story.append(Paragraph("No events recorded during this period.", normal_style))
    else:
        for idx, event in enumerate(data.events, 1):
            event_elements = []
            event_elements.append(Paragraph(f"EVENT {idx:02d}: {event.title}", item_title_style))
            
            details = [
                [Paragraph("<b>Category:</b>", normal_style), Paragraph(event.category or "N/A", normal_style)],
                [Paragraph("<b>Venue:</b>", normal_style), Paragraph(event.venue or "N/A", normal_style)],
                [Paragraph("<b>Date:</b>", normal_style), Paragraph(event.start_datetime.strftime('%d %B %Y') if event.start_datetime else "N/A", normal_style)],
                [Paragraph("<b>Status:</b>", normal_style), Paragraph(event.status or "N/A", normal_style)],
                [Paragraph("<b>Capacity:</b>", normal_style), Paragraph(str(event.max_participants) if event.max_participants else "Unlimited", normal_style)]
            ]
            t = Table(details, colWidths=[100, 300])
            t.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4)
            ]))
            event_elements.append(t)
            event_elements.append(Spacer(1, 5))
            
            # Description
            if event.short_description or event.description:
                desc_text = event.short_description if event.short_description else (event.description[:300] + "..." if len(event.description) > 300 else event.description)
                event_elements.append(Paragraph("<b>Description:</b>", normal_style))
                event_elements.append(Paragraph(desc_text, normal_style))
            
            event_elements.append(Spacer(1, 15))
            story.append(KeepTogether(event_elements))

    story.append(PageBreak())

    # ---------------------------------------------------------
    # 4. Registrations Section
    # ---------------------------------------------------------
    story.append(Paragraph("2. REGISTRATIONS", section_header_style))
    if not data.registration_summary:
        story.append(Paragraph("No registrations recorded during this period.", normal_style))
    else:
        reg_table_data = [["Event", "Date", "Registrations"]]
        for item in data.registration_summary:
            date_str = item["date"].strftime('%d %B %Y') if item["date"] else "N/A"
            reg_table_data.append([
                Paragraph(item["event_name"], normal_style),
                Paragraph(date_str, normal_style),
                str(item["total_registrations"])
            ])
            
        reg_table_data.append(["TOTAL", "", str(data.summary.total_registrations)])
        
        t = Table(reg_table_data, colWidths=[250, 150, 100], repeatRows=1)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), PRIMARY_COLOR),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (1, -1), 'LEFT'),
            ('ALIGN', (2, 0), (2, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('GRID', (0, 0), (-1, -2), 1, LIGHT_GRAY),
            # Total row styling
            ('LINEABOVE', (0, -1), (-1, -1), 2, PRIMARY_COLOR),
            ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ]))
        story.append(t)

    story.append(PageBreak())

    # ---------------------------------------------------------
    # 5. Startups Section
    # ---------------------------------------------------------
    story.append(Paragraph("3. STARTUPS", section_header_style))
    if not data.startups:
        story.append(Paragraph("No startups recorded during this period.", normal_style))
    else:
        for idx, startup in enumerate(data.startups, 1):
            st_elements = []
            st_elements.append(Paragraph(f"STARTUP {idx:02d}: {startup.name}", item_title_style))
            
            details = [
                [Paragraph("<b>Industry:</b>", normal_style), Paragraph(startup.industry or "N/A", normal_style)],
                [Paragraph("<b>Stage:</b>", normal_style), Paragraph(startup.stage.value if hasattr(startup.stage, 'value') else str(startup.stage), normal_style)],
                [Paragraph("<b>Status:</b>", normal_style), Paragraph(startup.status.value if hasattr(startup.status, 'value') else str(startup.status), normal_style)],
                [Paragraph("<b>Registered:</b>", normal_style), Paragraph(startup.created_at.strftime('%d %B %Y'), normal_style)]
            ]
            t = Table(details, colWidths=[100, 300])
            t.setStyle(TableStyle([('ALIGN', (0, 0), (-1, -1), 'LEFT'), ('VALIGN', (0, 0), (-1, -1), 'TOP')]))
            st_elements.append(t)
            
            if startup.founders:
                st_elements.append(Spacer(1, 10))
                st_elements.append(Paragraph("TEAM MEMBERS", bold_style))
                team_data = [["Name", "Role"]]
                for founder in startup.founders:
                    team_data.append([founder.name, founder.role or "Member"])
                
                team_t = Table(team_data, colWidths=[200, 200])
                team_t.setStyle(TableStyle([
                    ('LINEBELOW', (0, 0), (-1, 0), 1, PRIMARY_COLOR),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ]))
                st_elements.append(team_t)
            
            st_elements.append(Spacer(1, 20))
            story.append(KeepTogether(st_elements))

    story.append(PageBreak())

    # ---------------------------------------------------------
    # 6. Podcasts Section
    # ---------------------------------------------------------
    story.append(Paragraph("4. PODCASTS", section_header_style))
    if not data.podcasts:
        story.append(Paragraph("No podcasts recorded during this period.", normal_style))
    else:
        for idx, podcast in enumerate(data.podcasts, 1):
            pod_elements = []
            pod_elements.append(Paragraph(f"PODCAST {idx:02d}: {podcast.title}", item_title_style))
            
            details = [
                [Paragraph("<b>Date:</b>", normal_style), Paragraph(podcast.date_str or "N/A", normal_style)],
                [Paragraph("<b>Status:</b>", normal_style), Paragraph("Active" if podcast.is_active else "Draft", normal_style)]
            ]
            t = Table(details, colWidths=[100, 300])
            t.setStyle(TableStyle([('ALIGN', (0, 0), (-1, -1), 'LEFT'), ('VALIGN', (0, 0), (-1, -1), 'TOP')]))
            pod_elements.append(t)
            
            if podcast.description:
                pod_elements.append(Spacer(1, 5))
                pod_elements.append(Paragraph("<b>Description:</b>", normal_style))
                pod_elements.append(Paragraph(podcast.description, normal_style))
            
            pod_elements.append(Spacer(1, 15))
            story.append(KeepTogether(pod_elements))

    story.append(PageBreak())

    # ---------------------------------------------------------
    # 7. Announcements Section
    # ---------------------------------------------------------
    story.append(Paragraph("5. ANNOUNCEMENTS", section_header_style))
    if not data.announcements:
        story.append(Paragraph("No announcements recorded during this period.", normal_style))
    else:
        for idx, ann in enumerate(data.announcements, 1):
            ann_elements = []
            ann_elements.append(Paragraph(f"ANNOUNCEMENT {idx:02d}: {ann.title}", item_title_style))
            
            details = [
                [Paragraph("<b>Published:</b>", normal_style), Paragraph(ann.created_at.strftime('%d %B %Y'), normal_style)],
                [Paragraph("<b>Status:</b>", normal_style), Paragraph("Published" if ann.is_published else "Draft", normal_style)]
            ]
            t = Table(details, colWidths=[100, 300])
            t.setStyle(TableStyle([('ALIGN', (0, 0), (-1, -1), 'LEFT'), ('VALIGN', (0, 0), (-1, -1), 'TOP')]))
            ann_elements.append(t)
            
            if ann.content:
                ann_elements.append(Spacer(1, 5))
                ann_elements.append(Paragraph("<b>Description:</b>", normal_style))
                desc_text = ann.content[:300] + "..." if len(ann.content) > 300 else ann.content
                ann_elements.append(Paragraph(desc_text, normal_style))
            
            ann_elements.append(Spacer(1, 15))
            story.append(KeepTogether(ann_elements))
            
    story.append(PageBreak())

    # ---------------------------------------------------------
    # 8. Gallery Section
    # ---------------------------------------------------------
    story.append(Paragraph("6. GALLERY / ACTIVITIES", section_header_style))
    if not data.gallery:
        story.append(Paragraph("No gallery activities recorded during this period.", normal_style))
    else:
        for idx, item in enumerate(data.gallery, 1):
            gal_elements = []
            gal_elements.append(Paragraph(f"ACTIVITY {idx:02d}: {item.title or 'Untitled Activity'}", item_title_style))
            
            details = [
                [Paragraph("<b>Category:</b>", normal_style), Paragraph(item.category or "N/A", normal_style)],
                [Paragraph("<b>Date:</b>", normal_style), Paragraph(item.created_at.strftime('%d %B %Y'), normal_style)]
            ]
            t = Table(details, colWidths=[100, 300])
            t.setStyle(TableStyle([('ALIGN', (0, 0), (-1, -1), 'LEFT'), ('VALIGN', (0, 0), (-1, -1), 'TOP')]))
            gal_elements.append(t)
            
            if item.description:
                gal_elements.append(Spacer(1, 5))
                gal_elements.append(Paragraph("<b>Description:</b>", normal_style))
                gal_elements.append(Paragraph(item.description, normal_style))
            
            gal_elements.append(Spacer(1, 15))
            story.append(KeepTogether(gal_elements))

    # Build the PDF
    def add_page_number(canvas, doc):
        page_num = canvas.getPageNumber()
        
        # Header for internal pages
        if page_num > 1:
            canvas.saveState()
            
            # Draw header logo (small)
            canvas.drawImage(str(logo_path), 40, letter[1] - 40, width=25, height=25, preserveAspectRatio=True, mask='auto')
            
            # Draw header text
            canvas.setFont("Helvetica-Bold", 10)
            canvas.setFillColor(PRIMARY_COLOR)
            canvas.drawString(75, letter[1] - 30, "IEDC SNMIMT — Activity Report")
            
            # Draw header line
            canvas.setStrokeColor(PRIMARY_COLOR)
            canvas.setLineWidth(0.5)
            canvas.line(40, letter[1] - 45, letter[0] - 40, letter[1] - 45)
            
            canvas.restoreState()
            
        # Footer
        text = f"IEDC SNMIMT | Activity Report | Page {page_num}"
        canvas.saveState()
        canvas.setFont('Helvetica', 9)
        canvas.setFillColor(colors.gray)
        canvas.drawCentredString(letter[0] / 2.0, 30, text)
        canvas.restoreState()

    doc.build(story, onFirstPage=add_page_number, onLaterPages=add_page_number)
    
    buffer.seek(0)
    return buffer
