"""Apply SoftDeleteMixin and column_property

Revision ID: 05b4db6b7d17
Revises: 8e2e4d3fec4a
Create Date: 2026-07-24 18:19:58.502226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b4db6b7d17'
down_revision: Union[str, Sequence[str], None] = '8e2e4d3fec4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_announcements_deleted_at'), 'announcements', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_events_deleted_at'), 'events', ['deleted_at'], unique=False)
    op.add_column('startups', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_startups_deleted_at'), 'startups', ['deleted_at'], unique=False)
    op.add_column('team_members', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_team_members_deleted_at'), 'team_members', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_team_members_deleted_at'), table_name='team_members')
    op.drop_column('team_members', 'deleted_at')
    op.drop_index(op.f('ix_startups_deleted_at'), table_name='startups')
    op.drop_column('startups', 'deleted_at')
    op.drop_index(op.f('ix_events_deleted_at'), table_name='events')
    op.drop_index(op.f('ix_announcements_deleted_at'), table_name='announcements')
    # ### end Alembic commands ###
