"""Add About fields to WebsiteSettings

Revision ID: 178c970e2e50
Revises: bc20fe1c2ae7
Create Date: 2026-08-24 21:25:26.402713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178c970e2e50'
down_revision: Union[str, Sequence[str], None] = 'bc20fe1c2ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_settings', sa.Column('about_inspiration_quote', sa.Text(), nullable=True))
    op.add_column('website_settings', sa.Column('about_inspiration_author', sa.String(length=255), nullable=True))
    op.add_column('website_settings', sa.Column('about_inspiration_image_url', sa.String(length=1024), nullable=True))
    op.add_column('website_settings', sa.Column('about_values_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_settings', 'about_values_json')
    op.drop_column('website_settings', 'about_inspiration_image_url')
    op.drop_column('website_settings', 'about_inspiration_author')
    op.drop_column('website_settings', 'about_inspiration_quote')
    # ### end Alembic commands ###
