"""Add highly normalized Startup module and Batch

Revision ID: 311175f2b742
Revises: f1d35be2144d
Create Date: 2026-08-03 16:18:50.525681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311175f2b742'
down_revision: Union[str, Sequence[str], None] = 'f1d35be2144d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_created_at'), 'batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_batches_deleted_at'), 'batches', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_batches_is_active'), 'batches', ['is_active'], unique=False)
    op.create_index(op.f('ix_batches_name'), 'batches', ['name'], unique=True)
    op.create_table('technologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technologies_created_at'), 'technologies', ['created_at'], unique=False)
    op.create_index(op.f('ix_technologies_deleted_at'), 'technologies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_technologies_name'), 'technologies', ['name'], unique=True)
    op.create_table('startups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('tagline', sa.String(length=120), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('short_description', sa.String(length=300), nullable=False),
    sa.Column('full_description', sa.Text(), nullable=False),
    sa.Column('stage', sa.Enum('IDEA', 'PROTOTYPE', 'MVP', 'EARLY_REVENUE', 'SCALING', name='startupstage'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ALUMNI', 'INACTIVE', 'CLOSED', name='startupstatus'), nullable=False),
    sa.Column('registration_status', sa.Enum('REGISTERED', 'UNREGISTERED', 'INCORPORATED', name='startupregistrationstatus'), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('business_model', sa.Text(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('target_market', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('github_url', sa.String(length=512), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('instagram_url', sa.String(length=512), nullable=True),
    sa.Column('demo_video_url', sa.String(length=512), nullable=True),
    sa.Column('pitch_deck_url', sa.String(length=512), nullable=True),
    sa.Column('youtube_demo_url', sa.String(length=512), nullable=True),
    sa.Column('incubator', sa.String(length=255), nullable=True),
    sa.Column('clients', sa.Text(), nullable=True),
    sa.Column('patents', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('assigned_mentor_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_mentor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startups_created_at'), 'startups', ['created_at'], unique=False)
    op.create_index(op.f('ix_startups_deleted_at'), 'startups', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_startups_is_featured'), 'startups', ['is_featured'], unique=False)
    op.create_index(op.f('ix_startups_is_published'), 'startups', ['is_published'], unique=False)
    op.create_index(op.f('ix_startups_name'), 'startups', ['name'], unique=True)
    op.create_index(op.f('ix_startups_slug'), 'startups', ['slug'], unique=True)
    op.create_table('startup_awards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('awarded_by', sa.String(length=255), nullable=True),
    sa.Column('date_received', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_awards_created_at'), 'startup_awards', ['created_at'], unique=False)
    op.create_index(op.f('ix_startup_awards_deleted_at'), 'startup_awards', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_startup_awards_startup_id'), 'startup_awards', ['startup_id'], unique=False)
    op.create_table('startup_founders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('is_alumni', sa.Boolean(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_founders_created_at'), 'startup_founders', ['created_at'], unique=False)
    op.create_index(op.f('ix_startup_founders_deleted_at'), 'startup_founders', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_startup_founders_startup_id'), 'startup_founders', ['startup_id'], unique=False)
    op.create_table('startup_funding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('funding_round', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.String(length=255), nullable=True),
    sa.Column('investors', sa.Text(), nullable=True),
    sa.Column('date_received', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_funding_created_at'), 'startup_funding', ['created_at'], unique=False)
    op.create_index(op.f('ix_startup_funding_deleted_at'), 'startup_funding', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_startup_funding_startup_id'), 'startup_funding', ['startup_id'], unique=False)
    op.create_table('startup_gallery_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_gallery_images_created_at'), 'startup_gallery_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_startup_gallery_images_deleted_at'), 'startup_gallery_images', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_startup_gallery_images_is_published'), 'startup_gallery_images', ['is_published'], unique=False)
    op.create_index(op.f('ix_startup_gallery_images_startup_id'), 'startup_gallery_images', ['startup_id'], unique=False)
    op.create_table('startup_press_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('date_published', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_press_links_created_at'), 'startup_press_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_startup_press_links_deleted_at'), 'startup_press_links', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_startup_press_links_startup_id'), 'startup_press_links', ['startup_id'], unique=False)
    op.create_table('startup_technologies',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('startup_id', 'technology_id')
    )
    # op.add_column('users', sa.Column('is_mentor', sa.Boolean(), server_default='false', nullable=False))
    # op.create_index(op.f('ix_users_is_mentor'), 'users', ['is_mentor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_mentor'), table_name='users')
    op.drop_column('users', 'is_mentor')
    op.drop_table('startup_technologies')
    op.drop_index(op.f('ix_startup_press_links_startup_id'), table_name='startup_press_links')
    op.drop_index(op.f('ix_startup_press_links_deleted_at'), table_name='startup_press_links')
    op.drop_index(op.f('ix_startup_press_links_created_at'), table_name='startup_press_links')
    op.drop_table('startup_press_links')
    op.drop_index(op.f('ix_startup_gallery_images_startup_id'), table_name='startup_gallery_images')
    op.drop_index(op.f('ix_startup_gallery_images_is_published'), table_name='startup_gallery_images')
    op.drop_index(op.f('ix_startup_gallery_images_deleted_at'), table_name='startup_gallery_images')
    op.drop_index(op.f('ix_startup_gallery_images_created_at'), table_name='startup_gallery_images')
    op.drop_table('startup_gallery_images')
    op.drop_index(op.f('ix_startup_funding_startup_id'), table_name='startup_funding')
    op.drop_index(op.f('ix_startup_funding_deleted_at'), table_name='startup_funding')
    op.drop_index(op.f('ix_startup_funding_created_at'), table_name='startup_funding')
    op.drop_table('startup_funding')
    op.drop_index(op.f('ix_startup_founders_startup_id'), table_name='startup_founders')
    op.drop_index(op.f('ix_startup_founders_deleted_at'), table_name='startup_founders')
    op.drop_index(op.f('ix_startup_founders_created_at'), table_name='startup_founders')
    op.drop_table('startup_founders')
    op.drop_index(op.f('ix_startup_awards_startup_id'), table_name='startup_awards')
    op.drop_index(op.f('ix_startup_awards_deleted_at'), table_name='startup_awards')
    op.drop_index(op.f('ix_startup_awards_created_at'), table_name='startup_awards')
    op.drop_table('startup_awards')
    op.drop_index(op.f('ix_startups_slug'), table_name='startups')
    op.drop_index(op.f('ix_startups_name'), table_name='startups')
    op.drop_index(op.f('ix_startups_is_published'), table_name='startups')
    op.drop_index(op.f('ix_startups_is_featured'), table_name='startups')
    op.drop_index(op.f('ix_startups_deleted_at'), table_name='startups')
    op.drop_index(op.f('ix_startups_created_at'), table_name='startups')
    op.drop_table('startups')
    op.drop_index(op.f('ix_technologies_name'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_deleted_at'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_created_at'), table_name='technologies')
    op.drop_table('technologies')
    op.drop_index(op.f('ix_batches_name'), table_name='batches')
    op.drop_index(op.f('ix_batches_is_active'), table_name='batches')
    op.drop_index(op.f('ix_batches_deleted_at'), table_name='batches')
    op.drop_index(op.f('ix_batches_created_at'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
