"""Add custom_fields to events and custom_answers to registrations

Revision ID: 38d3a91ad024
Revises: 46d7d162eba2
Create Date: 2026-07-21 20:48:57.328769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d3a91ad024'
down_revision: Union[str, Sequence[str], None] = '46d7d162eba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('custom_fields', sa.JSON(), nullable=True))
    op.add_column('registrations', sa.Column('custom_answers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'custom_answers')
    op.drop_column('events', 'custom_fields')
    # ### end Alembic commands ###
