"""Add google forms and registration fields

Revision ID: 46d7d162eba2
Revises: b996975c444e
Create Date: 2026-07-21 19:25:14.705545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d7d162eba2'
down_revision: Union[str, Sequence[str], None] = 'b996975c444e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('google_form_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('events', sa.Column('google_form_url', sa.String(length=512), nullable=True))
    op.add_column('events', sa.Column('google_form_id', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('google_form_response_url', sa.String(length=512), nullable=True))
    op.add_column('events', sa.Column('field_mapping', sa.JSON(), nullable=True))
    op.add_column('events', sa.Column('sync_to_database', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('events', sa.Column('auto_detect_fields', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('registrations', sa.Column('gender', sa.String(length=50), nullable=True))
    op.add_column('registrations', sa.Column('year', sa.String(length=50), nullable=True))
    op.add_column('registrations', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('registrations', sa.Column('has_laptop', sa.Boolean(), nullable=True))
    op.add_column('registrations', sa.Column('is_iedc_member', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'is_iedc_member')
    op.drop_column('registrations', 'has_laptop')
    op.drop_column('registrations', 'department')
    op.drop_column('registrations', 'year')
    op.drop_column('registrations', 'gender')
    op.drop_column('events', 'auto_detect_fields')
    op.drop_column('events', 'sync_to_database')
    op.drop_column('events', 'field_mapping')
    op.drop_column('events', 'google_form_response_url')
    op.drop_column('events', 'google_form_id')
    op.drop_column('events', 'google_form_url')
    op.drop_column('events', 'google_form_enabled')
    # ### end Alembic commands ###
