"""update password reset schema

Revision ID: 6706e4343954
Revises: 311175f2b742
Create Date: 2026-08-04 09:57:18.147998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6706e4343954'
down_revision: Union[str, Sequence[str], None] = '311175f2b742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('hash_algorithm', sa.String(length=50), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('password_reset_tokens', 'is_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('password_reset_tokens', 'used_at')
    op.drop_column('password_reset_tokens', 'hash_algorithm')
    # ### end Alembic commands ###
