"""add about hero title

Revision ID: 76add0e800eb
Revises: 178c970e2e50
Create Date: 2026-08-25 09:15:18.801776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76add0e800eb'
down_revision: Union[str, Sequence[str], None] = '178c970e2e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_settings', sa.Column('about_hero_title', sa.String(length=512), nullable=True))
    op.add_column('website_settings', sa.Column('about_hero_highlight', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_settings', 'about_hero_highlight')
    op.drop_column('website_settings', 'about_hero_title')
    # ### end Alembic commands ###
