"""add_contact_message_fields_and_website_settings

Revision ID: 7bf34a55c4f9
Revises: ca4ad8094649
Create Date: 2026-07-26 09:59:29.326624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf34a55c4f9'
down_revision: Union[str, Sequence[str], None] = 'ca4ad8094649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('site_tagline', sa.String(length=512), nullable=True),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('favicon_url', sa.String(length=1024), nullable=True),
    sa.Column('hero_title', sa.String(length=512), nullable=True),
    sa.Column('hero_subtitle', sa.Text(), nullable=True),
    sa.Column('hero_cta_text', sa.String(length=100), nullable=True),
    sa.Column('hero_cta_link', sa.String(length=512), nullable=True),
    sa.Column('hero_image_url', sa.String(length=1024), nullable=True),
    sa.Column('about_description', sa.Text(), nullable=True),
    sa.Column('about_vision', sa.Text(), nullable=True),
    sa.Column('about_stats_json', sa.JSON(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_address', sa.Text(), nullable=True),
    sa.Column('facebook_url', sa.String(length=1024), nullable=True),
    sa.Column('instagram_url', sa.String(length=1024), nullable=True),
    sa.Column('twitter_url', sa.String(length=1024), nullable=True),
    sa.Column('linkedin_url', sa.String(length=1024), nullable=True),
    sa.Column('youtube_url', sa.String(length=1024), nullable=True),
    sa.Column('github_url', sa.String(length=1024), nullable=True),
    sa.Column('footer_tagline', sa.String(length=512), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('og_image_url', sa.String(length=1024), nullable=True),
    sa.Column('email_from_name', sa.String(length=255), nullable=True),
    sa.Column('email_reply_to', sa.String(length=255), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('google_analytics_id', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contact_messages', sa.Column('subject', sa.String(length=255), nullable=True))
    op.add_column('contact_messages', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.add_column('contact_messages', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.create_index(op.f('ix_contact_messages_is_archived'), 'contact_messages', ['is_archived'], unique=False)
    op.create_index(op.f('ix_contact_messages_is_read'), 'contact_messages', ['is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_messages_is_read'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_is_archived'), table_name='contact_messages')
    op.drop_column('contact_messages', 'ip_address')
    op.drop_column('contact_messages', 'is_archived')
    op.drop_column('contact_messages', 'subject')
    op.drop_table('website_settings')
    # ### end Alembic commands ###
