"""Update Startup schema and add StartupGalleryImage

Revision ID: 7ce562bd281e
Revises: 49a15049453b
Create Date: 2026-07-26 06:54:45.264348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ce562bd281e'
down_revision: Union[str, Sequence[str], None] = '49a15049453b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create Enum
    startupstage = postgresql.ENUM('IDEA', 'PROTOTYPE', 'MVP', 'EARLY_REVENUE', 'SCALING', name='startupstage')
    startupstage.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('startup_gallery_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_gallery_images_created_at'), 'startup_gallery_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_startup_gallery_images_deleted_at'), 'startup_gallery_images', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_startup_gallery_images_is_published'), 'startup_gallery_images', ['is_published'], unique=False)
    op.create_index(op.f('ix_startup_gallery_images_startup_id'), 'startup_gallery_images', ['startup_id'], unique=False)
    op.add_column('startups', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('startups', sa.Column('short_description', sa.String(length=300), nullable=False))
    op.add_column('startups', sa.Column('full_description', sa.Text(), nullable=False))
    op.add_column('startups', sa.Column('founders', sa.JSON(), nullable=True))
    op.add_column('startups', sa.Column('team_members', sa.JSON(), nullable=True))
    op.add_column('startups', sa.Column('stage', sa.Enum('IDEA', 'PROTOTYPE', 'MVP', 'EARLY_REVENUE', 'SCALING', name='startupstage'), nullable=False))
    op.add_column('startups', sa.Column('website_url', sa.String(length=512), nullable=True))
    op.add_column('startups', sa.Column('github_url', sa.String(length=512), nullable=True))
    op.add_column('startups', sa.Column('linkedin_url', sa.String(length=512), nullable=True))
    op.add_column('startups', sa.Column('demo_video_url', sa.String(length=512), nullable=True))
    op.add_column('startups', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('startups', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_startups_is_featured'), 'startups', ['is_featured'], unique=False)
    op.create_index(op.f('ix_startups_is_published'), 'startups', ['is_published'], unique=False)
    op.create_index(op.f('ix_startups_slug'), 'startups', ['slug'], unique=True)
    op.drop_column('startups', 'founder')
    op.drop_column('startups', 'description')
    op.drop_column('startups', 'website')
    op.drop_column('startups', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('startups', sa.Column('status', postgresql.ENUM('ACTIVE', 'ALUMNI', 'INACTIVE', name='startupstatus'), autoincrement=False, nullable=False))
    op.add_column('startups', sa.Column('website', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('startups', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('startups', sa.Column('founder', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_startups_slug'), table_name='startups')
    op.drop_index(op.f('ix_startups_is_published'), table_name='startups')
    op.drop_index(op.f('ix_startups_is_featured'), table_name='startups')
    op.drop_column('startups', 'is_featured')
    op.drop_column('startups', 'is_published')
    op.drop_column('startups', 'demo_video_url')
    op.drop_column('startups', 'linkedin_url')
    op.drop_column('startups', 'github_url')
    op.drop_column('startups', 'website_url')
    op.drop_column('startups', 'stage')
    op.drop_column('startups', 'team_members')
    op.drop_column('startups', 'founders')
    op.drop_column('startups', 'full_description')
    op.drop_column('startups', 'short_description')
    op.drop_column('startups', 'slug')
    op.drop_index(op.f('ix_startup_gallery_images_startup_id'), table_name='startup_gallery_images')
    op.drop_index(op.f('ix_startup_gallery_images_is_published'), table_name='startup_gallery_images')
    op.drop_index(op.f('ix_startup_gallery_images_deleted_at'), table_name='startup_gallery_images')
    op.drop_index(op.f('ix_startup_gallery_images_created_at'), table_name='startup_gallery_images')
    op.drop_table('startup_gallery_images')
    # ### end Alembic commands ###

    # Drop Enum
    startupstage = postgresql.ENUM('IDEA', 'PROTOTYPE', 'MVP', 'EARLY_REVENUE', 'SCALING', name='startupstage')
    startupstage.drop(op.get_bind(), checkfirst=True)
