"""Add category to team member

Revision ID: 8d46a90a3ca9
Revises: f943e055c2cc
Create Date: 2026-07-19 22:15:03.532173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d46a90a3ca9'
down_revision: Union[str, Sequence[str], None] = 'f943e055c2cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'category')
    # ### end Alembic commands ###
