"""Add cascade delete to event relationships

Revision ID: 8e2e4d3fec4a
Revises: 7ed31fa555c6
Create Date: 2026-07-24 18:10:20.751598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2e4d3fec4a'
down_revision: Union[str, Sequence[str], None] = '7ed31fa555c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('gallery_event_id_fkey'), 'gallery', type_='foreignkey')
    op.create_foreign_key(None, 'gallery', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('registrations_event_id_fkey'), 'registrations', type_='foreignkey')
    op.create_foreign_key(None, 'registrations', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('registrations_event_id_fkey'), 'registrations', type_='foreignkey')
    op.create_foreign_key(op.f('registrations_event_id_fkey'), 'registrations', 'events', ['event_id'], ['id'])
    op.drop_constraint(op.f('gallery_event_id_fkey'), 'gallery', type_='foreignkey')
    op.create_foreign_key(op.f('gallery_event_id_fkey'), 'gallery', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
