"""Add TokenBlocklist and Event fields

Revision ID: 909b8e899b2c
Revises: fc33362a7fc7
Create Date: 2026-07-25 17:55:16.218483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909b8e899b2c'
down_revision: Union[str, Sequence[str], None] = 'fc33362a7fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_token_blocklist_created_at'), 'token_blocklist', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blocklist_created_at'), table_name='token_blocklist')
    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
