"""add instagram_url to team members

Revision ID: 9d48fa9372e3
Revises: 7bf34a55c4f9
Create Date: 2026-07-26 21:51:05.011022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d48fa9372e3'
down_revision: Union[str, Sequence[str], None] = '7bf34a55c4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('instagram_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'instagram_url')
    # ### end Alembic commands ###
