"""add registration link to event

Revision ID: b996975c444e
Revises: 8d46a90a3ca9
Create Date: 2026-07-21 18:35:57.290938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b996975c444e'
down_revision: Union[str, Sequence[str], None] = '8d46a90a3ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('registration_link', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'registration_link')
    # ### end Alembic commands ###
