"""Add image_url to Podcast

Revision ID: bb1e532d362f
Revises: af0a136c7047
Create Date: 2026-07-21 21:43:04.594259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1e532d362f'
down_revision: Union[str, Sequence[str], None] = 'af0a136c7047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcasts', sa.Column('image_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcasts', 'image_url')
    # ### end Alembic commands ###
