"""add status to event

Revision ID: c68adde290f4
Revises: ddab93a66bf9
Create Date: 2026-08-09 11:37:23.350244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68adde290f4'
down_revision: Union[str, Sequence[str], None] = 'ddab93a66bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status', sa.String(length=50), nullable=False, server_default='DRAFT'))
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_column('events', 'status')
    # ### end Alembic commands ###
