"""extend_announcements

Revision ID: cfa4b0e1e592
Revises: f7f2b4c40983
Create Date: 2026-07-25 19:21:55.506860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa4b0e1e592'
down_revision: Union[str, Sequence[str], None] = 'f7f2b4c40983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('announcements', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('announcements', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('announcements', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('announcements', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_announcements_created_by'), 'announcements', ['created_by'], unique=False)
    op.create_index(op.f('ix_announcements_expires_at'), 'announcements', ['expires_at'], unique=False)
    op.create_index(op.f('ix_announcements_is_published'), 'announcements', ['is_published'], unique=False)
    op.create_index(op.f('ix_announcements_slug'), 'announcements', ['slug'], unique=True)
    op.create_foreign_key(None, 'announcements', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'announcements', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('events', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.add_column('startups', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'startups', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.add_column('team_members', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'team_members', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_by')
    op.drop_column('team_members', 'deleted_by')
    op.drop_column('startups', 'deleted_by')
    op.drop_column('events', 'deleted_by')
    op.drop_index(op.f('ix_announcements_slug'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_is_published'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_expires_at'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_created_by'), table_name='announcements')
    op.drop_column('announcements', 'deleted_by')
    op.drop_column('announcements', 'created_by')
    op.drop_column('announcements', 'expires_at')
    op.drop_column('announcements', 'is_published')
    op.drop_column('announcements', 'slug')
    # ### end Alembic commands ###
