"""add_partner_fields

Revision ID: ddab93a66bf9
Revises: 6706e4343954
Create Date: 2026-08-08 22:30:18.325431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddab93a66bf9'
down_revision: Union[str, Sequence[str], None] = '6706e4343954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('partners', sa.Column('website_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'website_url')
    op.drop_column('partners', 'description')
    # ### end Alembic commands ###
