"""Add GalleryImage model

Revision ID: e804be87b5d3
Revises: cfa4b0e1e592
Create Date: 2026-07-25 19:55:51.285340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e804be87b5d3'
down_revision: Union[str, Sequence[str], None] = 'cfa4b0e1e592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_images_category'), 'gallery_images', ['category'], unique=False)
    op.create_index(op.f('ix_gallery_images_created_at'), 'gallery_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_gallery_images_deleted_at'), 'gallery_images', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_gallery_images_event_id'), 'gallery_images', ['event_id'], unique=False)
    op.create_index(op.f('ix_gallery_images_is_published'), 'gallery_images', ['is_published'], unique=False)
    op.create_index(op.f('ix_gallery_images_title'), 'gallery_images', ['title'], unique=False)
    op.drop_index(op.f('ix_gallery_created_at'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_event_id'), table_name='gallery')
    op.drop_table('gallery')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('gallery_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('gallery_pkey'))
    )
    op.create_index(op.f('ix_gallery_event_id'), 'gallery', ['event_id'], unique=False)
    op.create_index(op.f('ix_gallery_created_at'), 'gallery', ['created_at'], unique=False)
    op.drop_index(op.f('ix_gallery_images_title'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_is_published'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_event_id'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_deleted_at'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_created_at'), table_name='gallery_images')
    op.drop_index(op.f('ix_gallery_images_category'), table_name='gallery_images')
    op.drop_table('gallery_images')
    # ### end Alembic commands ###
