"""Add hero_description

Revision ID: f1d35be2144d
Revises: 9d48fa9372e3
Create Date: 2026-07-27 19:47:04.169168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d35be2144d'
down_revision: Union[str, Sequence[str], None] = '9d48fa9372e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_settings', sa.Column('hero_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_settings', 'hero_description')
    # ### end Alembic commands ###
