"""extend_event_model

Revision ID: f7f2b4c40983
Revises: 505bc85fc269
Create Date: 2026-07-25 18:42:51.374222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7f2b4c40983'
down_revision: Union[str, Sequence[str], None] = '505bc85fc269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('slug', sa.String(length=255), nullable=True))
    op.execute("UPDATE events SET slug = id::text")
    op.alter_column('events', 'slug', nullable=False)
    op.add_column('events', sa.Column('short_description', sa.String(length=300), nullable=True))
    op.add_column('events', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('venue', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('events', sa.Column('created_by', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_created_by'), 'events', ['created_by'], unique=False)
    op.create_index(op.f('ix_events_is_published'), 'events', ['is_published'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_index(op.f('ix_events_start_datetime'), 'events', ['start_datetime'], unique=False)
    op.create_foreign_key('fk_events_created_by', 'events', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('events', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'REGISTRATION_OPEN', 'REGISTRATION_CLOSED', 'COMPLETED', 'CANCELLED', name='eventstatus'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_events_start_datetime'), table_name='events')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index(op.f('ix_events_is_published'), table_name='events')
    op.drop_index(op.f('ix_events_created_by'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.drop_column('events', 'created_by')
    op.drop_column('events', 'is_published')
    op.drop_column('events', 'end_datetime')
    op.drop_column('events', 'start_datetime')
    op.drop_column('events', 'venue')
    op.drop_column('events', 'category')
    op.drop_column('events', 'short_description')
    op.drop_column('events', 'slug')
    # ### end Alembic commands ###
