"""Add meta and email to team member

Revision ID: f943e055c2cc
Revises: 8780585ae4b6
Create Date: 2026-07-19 21:46:08.130727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f943e055c2cc'
down_revision: Union[str, Sequence[str], None] = '8780585ae4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('meta', sa.String(length=255), nullable=True))
    op.add_column('team_members', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'email')
    op.drop_column('team_members', 'meta')
    # ### end Alembic commands ###
