"""Add indexes to created_at and event_id

Revision ID: fc33362a7fc7
Revises: 05b4db6b7d17
Create Date: 2026-07-24 19:15:19.883152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc33362a7fc7'
down_revision: Union[str, Sequence[str], None] = '05b4db6b7d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_announcements_created_at'), 'announcements', ['created_at'], unique=False)
    op.create_index(op.f('ix_contact_messages_created_at'), 'contact_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_gallery_created_at'), 'gallery', ['created_at'], unique=False)
    op.create_index(op.f('ix_gallery_event_id'), 'gallery', ['event_id'], unique=False)
    op.create_index(op.f('ix_partners_created_at'), 'partners', ['created_at'], unique=False)
    op.create_index(op.f('ix_podcasts_created_at'), 'podcasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_registrations_created_at'), 'registrations', ['created_at'], unique=False)
    op.create_index(op.f('ix_startups_created_at'), 'startups', ['created_at'], unique=False)
    op.create_index(op.f('ix_team_members_created_at'), 'team_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_team_members_created_at'), table_name='team_members')
    op.drop_index(op.f('ix_startups_created_at'), table_name='startups')
    op.drop_index(op.f('ix_registrations_created_at'), table_name='registrations')
    op.drop_index(op.f('ix_podcasts_created_at'), table_name='podcasts')
    op.drop_index(op.f('ix_partners_created_at'), table_name='partners')
    op.drop_index(op.f('ix_gallery_event_id'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_created_at'), table_name='gallery')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index(op.f('ix_contact_messages_created_at'), table_name='contact_messages')
    op.drop_index(op.f('ix_announcements_created_at'), table_name='announcements')
    # ### end Alembic commands ###
